# Generated by Django 4.2.2 on 2023-06-17 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_alter_movieorder_buyed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["id"]},
        ),
    ]
